#-------------------------------
# Site Settings
title: Temjana Angjusheva
logo: "/images/logo.png" # You can add own logo. For example "/images/logo.svg".
logo_dark: "/images/logo.png"
description: Temi Design by Temjana Angjusheva
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the users can choose the light or dark mode themself.


#-------------------------------
# Author Settings
author_name: Temjana Angjusheva


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: "Home"
      url: "/"
    - title: "Projects"
      url: "/projects/"
    - title: "Blog"
      url: "/blog/"
    - title: "About"
      url: "/about/"

#-------------------------------
# Social Settings
social:
- {icon: "fa-brands fa-instagram", link: "https://www.instagram.com/tapas_visuals/"}
- {icon: "fa-brands fa-dribbble", link: "https://dribbble.com/temiang"}
- {icon: "fa-brands fa-linkedin", link: "https://www.linkedin.com/in/temjana-angjusheva/"}
- {icon: "fa-brands fa-behance", link: "https://behance.com/temjanaangjush"} 

# Example of adding a new link to the header and footer - {icon: "fa-brands fa-youtube", link: "https://youtube.com"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_title: Hey, I'm Temi. I Design <span><i>Digital Products & Brands</i></span> # Add the "span" tag to highlight text.
  hero_description: A UX & Visual Brand Designer focused on designing simple, scalable mobile and web products, as well as creating beautiful, bold designs that help brands grow.
  hero_image: "/images/main-image.webp" # Title background image
  hero_button_contact: Get In Touch
  hero_button_about: About Me


#-------------------------------
# Projects Settings
section_projects_title: 👨🏻‍💻 Portfolio


#-------------------------------
# Testimonials Section
section_testimonial_title: 🧚🏻‍♀️ Services

testimonial_items:
  - name: "Branding (and Packaging Design)"
    image: "/images/testimonials/branding_img.png"
    designation: "You deserve a banger of a brand!"
    #--link: "https://www.linkedin.com/in/hristijan-p-295182147/"
    content : "Whether you've got a brilliant idea for you new brand, or you want a refreshment to your existing one - you've found your gal. Through research and strategizing, I'll help you craft your brand's unique visual identity that perfectly captures your essence and captivates your customers."

  - name: "Marketing Design"
    image: "/images/testimonials/marketing_img.png"
    designation: "What better than a snatched online presence?"
   #-- link: "https://www.linkedin.com/in/anastasija-mladenovska-51660924a/"
    content : "Need engaging graphics that make your brand stand out? You got it. I create everything from social media posts, website graphics, email design to printed materials like posters, flyers and brochures. I develop designs that boost your brand’s visibility and communication, ensuring your materials are both eye-catching and effective."

  - name: "UI/UX Design"
    image: "/images/testimonials/ux_img.png"
    designation: "Attract. Convert. Grow."
    #--link: "https://www.linkedin.com/in/anastasija-mladenovska-51660924a/"
    content : "I design data-driven websites and mobile applications (Android & iOS) that look amazing, convert and are super easy to use. Every design is backed up by lots of hours of research and usability testing to create user-friendly, intuitive experiences."
#-------------------------------
#-------------------------------
# Blog Section
#section_blog_title: 📚 Read Latest Posts
#-------------------------------


# Tags Section
section_tags_title: ✌️ Explore Topics


#-------------------------------
# Newsletter Settings
#mailchimp_settings:
#  enable: true
#  mailchimp_title: Join my email list
#  mailchimp_identifier:  # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
#  mailchimp_input_text: Enter your email address
#  mailchimp_background_image: /images/subscribe-bg.jpg

#-------------------------------
# Footer Settings
footer_description: I’m Temi, and I'm glad you're here. I transform ideas into visually compelling narratives, blending creativity with precision to communicate messages that resonate.


#-------------------------------
# Footer Navigation Settings
footer_menu_settings:
  menu_items:
    - title: "Home"
      url: "/"
    - title: "Projects"
      url: "/projects/"
    - title: "Blog"
      url: "/blog/"
    - title: "About"
      url: "/about/"

#-------------------------------
# Contact Settings
contact:
  email: temi.angjusheva@gmail.com # Add your form_id
  description: #Simpler comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form

# NOTE
# Simpler theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus_identifier: # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google_analytics: # Add your GA Tracking Id
