#-------------------------------
# Site Settings
title: Temjana Angjusheva
logo: "/images/logo.png" # You can add own logo. For example "/images/logo.svg".
logo_dark: "/images/logo.png"
description: Temi Design by Temjana Angjusheva
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the users can choose the light or dark mode themself.


#-------------------------------
# Author Settings
author_name: Temjana Angjusheva


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: "Home"
      url: "/"
    - title: "Projects"
      url: "/projects/"
    - title: "Blog"
      url: "/blog/"
    - title: "About"
      url: "/about/"

#-------------------------------
# Social Settings
social:
- {icon: "fa-brands fa-instagram", link: "https://www.instagram.com/tapas_visuals/"}
- {icon: "fa-brands fa-dribbble", link: "https://dribbble.com/temiang"}
- {icon: "fa-brands fa-linkedin", link: "https://linkedin.com/temjanaangjusheva"}
- {icon: "fa-brands fa-behance", link: "https://behance.com/temjanaangjush"}

# Example of adding a new link to the header and footer - {icon: "fa-brands fa-youtube", link: "https://youtube.com"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_title: Hey, I'm Temi. I Design <span><i>Digital Products & Brands</i></span> # Add the "span" tag to highlight text.
  hero_description: A UX & Visual Brand Designer focused on designing simple, scalable mobile and web products, as well as creating beautiful, bold designs that help brands grow.
  hero_image: "/images/main-image.webp" # Title background image
  hero_button_contact: Get In Touch
  hero_button_about: About Me


#-------------------------------
# Projects Settings
section_projects_title: 👨🏻‍💻 Selected Works


#-------------------------------
# Testimonials Section
section_testimonial_title: 🗣️ What Others Say

testimonial_items:
  - name: "Hristijan Petrovski"
    image: "/images/testimonials/client-1.jpg"
    designation: "CEO @ ByteFengs"
    link: "https://www.linkedin.com/in/hristijan-p-295182147/"
    content : "I had the pleasure of working with Temjana on a recent project. She was an absolute pleasure to work with. Her skills in graphics design and UI/UX were invaluable to the success of the project. She was able to take our ideas and bring them to life in a way that exceeded our expectations. Her attention to detail and dedication to the project was impressive. I would highly recommend Temjana for any project that requires her skills."

  - name: "Anastasija Mladenovska"
    image: "/images/testimonials/client-2.jpg"
    designation: "Political Science PhD @Miami University"
    link: "https://www.linkedin.com/in/anastasija-mladenovska-51660924a/"
    content : "I recently worked with Temjana on a brand design project and I was extremely impressed with the results. She was able to deliver an excellent design that met all of my expectations and was completed on time. I would highly recommend her for any brand design project!"

#-------------------------------
# Blog Section
#section_blog_title: 📚 Read Latest Posts
#-------------------------------


# Tags Section
section_tags_title: ✌️ Explore Topics


#-------------------------------
# Newsletter Settings
#mailchimp_settings:
#  enable: true
#  mailchimp_title: Join my email list
#  mailchimp_identifier:  # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
#  mailchimp_input_text: Enter your email address
#  mailchimp_background_image: /images/subscribe-bg.jpg

#-------------------------------
# Footer Settings
footer_description: I’m Temi, and I'm glad you're here. I transform ideas into visually compelling narratives, blending creativity with precision to communicate messages that resonate.


#-------------------------------
# Footer Navigation Settings
footer_menu_settings:
  menu_items:
    - title: "Home"
      url: "/"
    - title: "Projects"
      url: "/projects/"
    - title: "Blog"
      url: "/blog/"
    - title: "About"
      url: "/about/"

#-------------------------------
# Contact Settings
contact:
  email: temi.angjusheva@gmail.com # Add your form_id
  description: #Simpler comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form

# NOTE
# Simpler theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus_identifier: # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google_analytics: # Add your GA Tracking Id
